package org.fastcampus.springstarter.entity;

import jakarta.persistence.*;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity //  Hibernate -> Table mapping
@Getter
@Setter
@NoArgsConstructor
public class Book { // VO, DTO
    @Id  // Primary Key(기본키)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String subject;
    private int price;
    private String author;
    private int page;
    private LocalDateTime createdAt; //클래스 : 카멜케이스(표기법) - DB(테이블) : 스네이크케이스(표기법)

    @OneToMany(mappedBy = "book", cascade = CascadeType.ALL)
    private List<Review> reviews;
}
/*
 create table book (
        page integer not null,
        price integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        author varchar(255),
        subject varchar(255),
        primary key (id)
    )
 */