package org.fastcampus.springstarter.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Setter
@Getter
@NoArgsConstructor
public class Review {  // create table review ~ SQL
    @Id // PK
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // 리뷰 일년번호, 1,2,3,4(자동증가, PK)

    private String content; // 리뷰 내용
    private int rating; // 평점(1~5)
    private LocalDateTime createdAt; // 작성일자

    @ManyToOne
    // FK : book_id
    @JoinColumn(name = "book_id", referencedColumnName = "id", nullable = false)
    private Book book; // Book(id)->book.id

}
/*
 create table review (
        rating integer not null,
        book_id bigint not null,  FK(외래키)
        created_at timestamp(6),
        id bigint generated by default as identity,
        content varchar(255),
        primary key (id)
    )

 alter table if exists review
       add constraint FK70yrt09r4r54tcgkrwbeqenbs
       foreign key (book_id)
       references book(id)
 */